const fs = require('fs');

const content = [
  'import { expect } from "chai";',
  'import { loadFixture, time } from "@nomicfoundation/hardhat-network-helpers";',
  'import { ethers, upgrades } from "hardhat";',
  'import { SignerWithAddress } from "@nomicfoundation/hardhat-ethers/signers";',
  '',
  'describe("PiggyVault", function () {',
  '  let asset: any;',
  '  let mockAdapter: any;',
  '  let vault: any;',
  '  let admin: SignerWithAddress;',
  '  let operator: SignerWithAddress;',
  '  let user: SignerWithAddress;',
  '  let borrower: SignerWithAddress;',
  '  let other: SignerWithAddress;',
  '',
  '  async function deployFixture() {',
  '    const signers = await ethers.getSigners();',
  '    const _admin = signers[0];',
  '    const _operator = signers[1];',
  '    const _user = signers[2];',
  '    const _borrower = signers[3];',
  '    const _other = signers[4];',
  '',
  '    const F1 = await ethers.getContractFactory("MockERC20");',
  '    const _asset = await F1.deploy("USD Coin", "USDC", 6);',
  '    await _asset.waitForDeployment();',
  '    const assetAddr = await _asset.getAddress();',
  '',
  '    const F2 = await ethers.getContractFactory("MockAaveAdapter");',
  '    const _mockAdapter = await F2.deploy();',
  '    await _mockAdapter.waitForDeployment();',
  '    await _mockAdapter.setAsset(assetAddr);',
  '    const maAddr = await _mockAdapter.getAddress();',
  '',
  '    const VF = await ethers.getContractFactory("PiggyVault");',
  '    const _vault = await upgrades.deployProxy(',
  '      VF,',
  '      [assetAddr, _admin.address],',
  '      { kind: "uups", initializer: "initialize" }',
  '    );',
  '    await _vault.waitForDeployment();',
  '',
  '    const opRole = await _vault.OPERATOR_ROLE();',
  '    await _vault.connect(_admin).grantRole(opRole, _operator.address);',
  '    await _vault.connect(_admin).setYieldAdapter(maAddr);',
  '',
  '    return { _asset, _mockAdapter, _vault, _admin, _operator, _user, _borrower, _other };',
  '  }',
  '',
  '  beforeEach(async function () {',
  '    const f = await loadFixture(deployFixture);',
  '    asset = f._asset;',
  '    mockAdapter = f._mockAdapter;',
  '    vault = f._vault;',
  '    admin = f._admin;',
  '    operator = f._operator;',
  '    user = f._user;',
  '    borrower = f._borrower;',
  '    other = f._other;',
  '  });',
  '',
  '  describe("Deployment", function () {',
  '    it("should set the correct asset and admin", async function () {',
  '      expect(await vault.asset()).to.equal(await asset.getAddress());',
  '      expect(await vault.hasRole(await vault.DEFAULT_ADMIN_ROLE(), admin.address)).to.be.true;',
  '    });',
  '    it("should have zero initial balance", async function () {',
  '      expect(await vault.totalAssets()).to.equal(0);',
  '    });',
  '    it("should revert reinitialization (UUPS)", async function () {',
  '      const VF = await ethers.getContractFactory("PiggyVault");',
  '      const addr = await vault.getAddress();',
  '      const aAddr = await asset.getAddress();',
  '      await expect(',
  '        upgrades.upgradeProxy(addr, VF, {',
  '          kind: "uups",',
  '          call: { fn: "initialize", args: [aAddr, admin.address] },',
  '        })',
  '      ).to.be.revertedWith("Initializable: contract is already initialized");',
  '    });',
  '  });',
  '',
  '  describe("Deposits", function () {',
  '    it("should allow deposits", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await expect(() => vault.connect(user).deposit(amount, user.address)',
  '      ).to.changeTokenBalance(asset, vault, amount);',
  '    });',
  '    it("should mint internal shares 1:1", async function () {',
  '      const amount = ethers.parseUnits("500", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      expect(await vault.internalShares(user.address)).to.equal(amount);',
  '    });',
  '    it("should revert zero deposit", async function () {',
  '      await asset.connect(user).approve(await vault.getAddress(), 0);',
  '      await expect(',
  '        vault.connect(user).deposit(0, user.address)',
  '      ).to.be.revertedWithCustomError(vault, "ZeroAmount");',
  '    });',
  '  });',
  '',
  '  describe("enableYield", function () {',
  '    it("should enable yield with dead shares protection", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      const DS = 1000n;',
  '      expect(await vault.supplyShares(user.address)).to.equal(amount - DS);',
  '      expect(await vault.supplyShares(ethers.ZeroAddress)).to.equal(DS);',
  '      expect(await vault.yieldEnabled(user.address)).to.be.true;',
  '    });',
  '    it("should revert if no balance", async function () {',
  '      await expect(vault.connect(other).enableYield(100)',
  '      ).to.be.revertedWithCustomError(vault, "InsufficientBalance");',
  '    });',
  '    it("should revert zero amount", async function () {',
  '      await expect(vault.connect(other).enableYield(0)',
  '      ).to.be.revertedWithCustomError(vault, "ZeroAmount");',
  '    });',
  '    it("should revert double enable", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      await expect(vault.connect(user).enableYield(100)',
  '      ).to.be.revertedWithCustomError(vault, "YieldAlreadyEnabled");',
  '    });',
  '  });',
  '',
  '  describe("disableAllYield", function () {',
  '    it("should disable yield and move funds", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      await mockAdapter.setSuppliedValue(amount);',
  '      await vault.connect(user).disableAllYield();',
  '      expect(await vault.yieldEnabled(user.address)).to.be.false;',
  '      expect(await vault.supplyShares(user.address)).to.equal(0);',
  '      expect(await vault.internalShares(user.address)).to.be.gt(0);',
  '    });',
  '    it("should revert if not enabled", async function () {',
  '      await expect(vault.connect(other).disableAllYield()',
  '      ).to.be.revertedWithCustomError(vault, "NoYieldPosition");',
  '    });',
  '  });',
  '',
  '  describe("disableYield", function () {',
  '    it("should disable partial yield", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      await mockAdapter.setSuppliedValue(amount);',
  '      await vault.connect(user).disableYield(amount / 2n);',
  '      expect(await vault.yieldEnabled(user.address)).to.be.true;',
  '    });',
  '    it("should revert if over-withdrawing", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      await mockAdapter.setSuppliedValue(amount);',
  '      await expect(vault.connect(user).disableYield(amount + 1n)',
  '      ).to.be.revertedWithCustomError(vault, "InsufficientShares");',
  '    });',
  '  });',
  '',
  '  describe("Borrow and Repay", function () {',
  '    async function fundAndEnable() {',
  '      const amount = ethers.parseUnits("10000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '    }',
  '    it("should allow borrow", async function () {',
  '      await fundAndEnable();',
  '      const bAmt = ethers.parseUnits("5000", 6);',
  '      await expect(() => vault.connect(borrower).borrow(bAmt, borrower.address)',
  '      ).to.changeTokenBalance(asset, borrower, bAmt);',
  '    });',
  '    it("should track debt correctly", async function () {',
  '      await fundAndEnable();',
  '      const bAmt = ethers.parseUnits("5000", 6);',
  '      await vault.connect(borrower).borrow(bAmt, borrower.address);',
  '      expect(await vault.debtShares(borrower.address)).to.equal(bAmt);',
  '      expect(await vault.totalDebt()).to.equal(bAmt);',
  '    });',
  '    it("should allow repay", async function () {',
  '      await fundAndEnable();',
  '      const bAmt = ethers.parseUnits("5000", 6);',
  '      await vault.connect(borrower).borrow(bAmt, borrower.address);',
  '      const rAmt = ethers.parseUnits("2000", 6);',
  '      await asset.connect(borrower).approve(await vault.getAddress(), rAmt);',
  '      await vault.connect(borrower).repay(rAmt, borrower.address);',
  '    });',
  '    it("should revert zero borrow", async function () {',
  '      await expect(vault.connect(borrower).borrow(0, borrower.address)',
  '      ).to.be.revertedWithCustomError(vault, "ZeroAmount");',
  '    });',
  '  });',
  '',
  '  describe("Access Control", function () {',
  '    it("should reject non-admin setYieldAdapter", async function () {',
  '      await expect(vault.connect(user).setYieldAdapter(ethers.ZeroAddress)',
  '      ).to.be.revertedWithCustomError(vault, "AccessControlUnauthorizedAccount");',
  '    });',
  '    it("should reject non-admin setTotalDepositCap", async function () {',
  '      await expect(vault.connect(user).setTotalDepositCap(1000)',
  '      ).to.be.revertedWithCustomError(vault, "AccessControlUnauthorizedAccount");',
  '    });',
  '    it("should reject non-operator rebalanceYield", async function () {',
  '      await expect(vault.connect(user).rebalanceYield(100)',
  '      ).to.be.revertedWithCustomError(vault, "AccessControlUnauthorizedAccount");',
  '    });',
  '    it("should reject zero address deposit", async function () {',
  '      const amount = ethers.parseUnits("100", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await expect(vault.connect(user).deposit(amount, ethers.ZeroAddress)',
  '      ).to.be.revertedWithCustomError(vault, "ZeroAddress");',
  '    });',
  '  });',
  '',
  '  describe("maxTotalDeposits", function () {',
  '    it("should enforce deposit cap", async function () {',
  '      await vault.connect(admin).setTotalDepositCap(ethers.parseUnits("500", 6));',
  '      await asset.connect(user).approve(await vault.getAddress(), ethers.parseUnits("600", 6));',
  '      await expect(vault.connect(user).deposit(ethers.parseUnits("600", 6), user.address)',
  '      ).to.be.revertedWithCustomError(vault, "CapExceedsCurrentBalance");',
  '    });',
  '  });',
  '});',
  ''
];

fs.writeFileSync('test/PiggyVault.test.ts', content.join('\n'));
console.log('Written', fs.statSync('test/PiggyVault.test.ts').size, 'bytes');
