const fs = require('fs');

const content = [
  'import { expect } from "chai";',
  'import { loadFixture, time } from "@nomicfoundation/hardhat-network-helpers";',
  'import { ethers, upgrades } from "hardhat";',
  'import { SignerWithAddress } from "@nomicfoundation/hardhat-ethers/signers";',
  '',
  'describe("PiggyVault", function () {',
  '  let asset: any;',
  '  let mockAdapter: any;',
  '  let vault: any;',
  '  let admin: SignerWithAddress;',
  '  let operator: SignerWithAddress;',
  '  let user: SignerWithAddress;',
  '  let borrower: SignerWithAddress;',
  '  let other: SignerWithAddress;',
  '',
  '  async function deployFixture() {',
  '    const signers = await ethers.getSigners();',
  '    const _admin = signers[0];',
  '    const _operator = signers[1];',
  '    const _user = signers[2];',
  '    const _borrower = signers[3];',
  '    const _other = signers[4];',
  '',
  '    const MockERC20Factory = await ethers.getContractFactory("MockERC20");',
  '    const _asset = await MockERC20Factory.deploy("USD Coin", "USDC", 6);',
  '    await _asset.waitForDeployment();',
  '',
  '    const MockAaveAdapterFactory = await ethers.getContractFactory("MockAaveAdapter");',
  '    const _mockAdapter = await MockAaveAdapterFactory.deploy(await _asset.getAddress());',
  '    await _mockAdapter.waitForDeployment();',
  '',
  '    const PiggyVaultFactory = await ethers.getContractFactory("PiggyVault");',
  '    const _vault = await upgrades.deployProxy(',
  '      PiggyVaultFactory,',
  '      [await _asset.getAddress(), _admin.address],',
  '      { kind: "uups", initializer: "initialize" }',
  '    );',
  '    await _vault.waitForDeployment();',
  '',
  '    await _vault.connect(_admin).grantRole(await _vault.OPERATOR_ROLE(), _operator.address);',
  '    await _vault.connect(_admin).setYieldAdapter(await _mockAdapter.getAddress());',
  '',
  '    return { _asset, _mockAdapter, _vault, _admin, _operator, _user, _borrower, _other };',
  '  }',
  '',
  '  beforeEach(async function () {',
  '    const f = await loadFixture(deployFixture);',
  '    asset = f._asset;',
  '    mockAdapter = f._mockAdapter;',
  '    vault = f._vault;',
  '    admin = f._admin;',
  '    operator = f._operator;',
  '    user = f._user;',
  '    borrower = f._borrower;',
  '    other = f._other;',
  '  });',
  '',
  '  describe("Deployment", function () {',
  '    it("should set the correct asset and admin", async function () {',
  '      expect(await vault.asset()).to.equal(await asset.getAddress());',
  '      expect(await vault.hasRole(await vault.DEFAULT_ADMIN_ROLE(), admin.address)).to.be.true;',
  '    });',
  '',
  '    it("should have zero initial balance", async function () {',
  '      expect(await vault.totalAssets()).to.equal(0);',
  '    });',
  '',
  '    it("should revert when initializing twice (UUPS)", async function () {',
  '      const PiggyVaultFactory = await ethers.getContractFactory("PiggyVault");',
  '      await expect(',
  '        upgrades.upgradeProxy(await vault.getAddress(), PiggyVaultFactory, {',
  '          kind: "uups",',
  '          call: { fn: "initialize", args: [await asset.getAddress(), admin.address] },',
  '        })',
  '      ).to.be.revertedWith("Initializable: contract is already initialized");',
  '    });',
  '  });',
  '',
  '  describe("Deposits", function () {',
  '    it("should allow deposits", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await expect(() =>',
  '        vault.connect(user).deposit(amount, user.address)',
  '      ).to.changeTokenBalance(asset, vault, amount);',
  '    });',
  '',
  '    it("should mint correct internal shares", async function () {',
  '      const amount = ethers.parseUnits("500", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      expect(await vault.internalShares(user.address)).to.equal(amount);',
  '    });',
  '',
  '    it("should revert deposit with zero amount", async function () {',
  '      await asset.connect(user).approve(await vault.getAddress(), 0);',
  '      await expect(',
  '        vault.connect(user).deposit(0, user.address)',
  '      ).to.be.revertedWithCustomError(vault, "ZeroAmount");',
  '    });',
  '  });',
  '',
  '  describe("enableYield", function () {',
  '    it("should allow user to enable yield", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      const DEAD_SHARES = 1000n;',
  '      expect(await vault.supplyShares(user.address)).to.equal(amount - DEAD_SHARES);',
  '      expect(await vault.supplyShares(ethers.ZeroAddress)).to.equal(DEAD_SHARES);',
  '      expect(await vault.yieldEnabled(user.address)).to.be.true;',
  '    });',
  '',
  '    it("should revert enableYield when not deposited", async function () {',
  '      await expect(',
  '        vault.connect(other).enableYield(100)',
  '      ).to.be.revertedWithCustomError(vault, "InsufficientBalance");',
  '    });',
  '',
  '    it("should revert enableYield with zero amount", async function () {',
  '      await expect(',
  '        vault.connect(other).enableYield(0)',
  '      ).to.be.revertedWithCustomError(vault, "ZeroAmount");',
  '    });',
  '',
  '    it("should revert when enabling yield twice", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      await expect(',
  '        vault.connect(user).enableYield(100)',
  '      ).to.be.revertedWithCustomError(vault, "YieldAlreadyEnabled");',
  '    });',
  '  });',
  '',
  '  describe("disableAllYield", function () {',
  '    it("should disable yield and return funds", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      await mockAdapter.setSuppliedValue(amount);',
  '      await vault.connect(user).disableAllYield();',
  '      expect(await vault.yieldEnabled(user.address)).to.be.false;',
  '      expect(await vault.supplyShares(user.address)).to.equal(0);',
  '      expect(await vault.internalShares(user.address)).to.be.gt(0);',
  '    });',
  '',
  '    it("should revert when yield not enabled", async function () {',
  '      await expect(',
  '        vault.connect(other).disableAllYield()',
  '      ).to.be.revertedWithCustomError(vault, "NoYieldPosition");',
  '    });',
  '  });',
  '',
  '  describe("disableYield", function () {',
  '    it("should disable partial yield", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      await mockAdapter.setSuppliedValue(amount);',
  '      const halfAmount = amount / 2n;',
  '      await vault.connect(user).disableYield(halfAmount);',
  '      expect(await vault.yieldEnabled(user.address)).to.be.true;',
  '    });',
  '',
  '    it("should revert when disabling more than enabled", async function () {',
  '      const amount = ethers.parseUnits("1000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      await mockAdapter.setSuppliedValue(amount);',
  '      await expect(',
  '        vault.connect(user).disableYield(amount + 1n)',
  '      ).to.be.revertedWithCustomError(vault, "InsufficientShares");',
  '    });',
  '  });',
  '',
  '  describe("Borrow and Repay", function () {',
  '    it("should allow borrow", async function () {',
  '      const amount = ethers.parseUnits("10000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      const borrowAmount = ethers.parseUnits("5000", 6);',
  '      await expect(() =>',
  '        vault.connect(borrower).borrow(borrowAmount, borrower.address)',
  '      ).to.changeTokenBalance(asset, borrower, borrowAmount);',
  '    });',
  '',
  '    it("should track debt correctly", async function () {',
  '      const amount = ethers.parseUnits("10000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      const borrowAmount = ethers.parseUnits("5000", 6);',
  '      await vault.connect(borrower).borrow(borrowAmount, borrower.address);',
  '      expect(await vault.debtShares(borrower.address)).to.equal(borrowAmount);',
  '      expect(await vault.totalDebt()).to.equal(borrowAmount);',
  '    });',
  '',
  '    it("should allow repay", async function () {',
  '      const amount = ethers.parseUnits("10000", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await vault.connect(user).deposit(amount, user.address);',
  '      await vault.connect(user).enableYield(amount);',
  '      const borrowAmount = ethers.parseUnits("5000", 6);',
  '      await vault.connect(borrower).borrow(borrowAmount, borrower.address);',
  '      const repayAmount = ethers.parseUnits("2000", 6);',
  '      await asset.connect(borrower).approve(await vault.getAddress(), repayAmount);',
  '      await vault.connect(borrower).repay(repayAmount, borrower.address);',
  '    });',
  '',
  '    it("should revert borrow with zero amount", async function () {',
  '      await expect(',
  '        vault.connect(borrower).borrow(0, borrower.address)',
  '      ).to.be.revertedWithCustomError(vault, "ZeroAmount");',
  '    });',
  '  });',
  '',
  '  describe("Access Control", function () {',
  '    it("should not allow non-admin to set adapter", async function () {',
  '      await expect(',
  '        vault.connect(user).setYieldAdapter(ethers.ZeroAddress)',
  '      ).to.be.revertedWithCustomError(',
  '        vault,',
  '        "AccessControlUnauthorizedAccount"',
  '      );',
  '    });',
  '',
  '    it("should not allow non-admin to set total deposit cap", async function () {',
  '      await expect(',
  '        vault.connect(user).setTotalDepositCap(1000)',
  '      ).to.be.revertedWithCustomError(',
  '        vault,',
  '        "AccessControlUnauthorizedAccount"',
  '      );',
  '    });',
  '',
  '    it("should not allow non-operator to trigger yield rebalance", async function () {',
  '      await expect(',
  '        vault.connect(user).rebalanceYield(100)',
  '      ).to.be.revertedWithCustomError(',
  '        vault,',
  '        "AccessControlUnauthorizedAccount"',
  '      );',
  '    });',
  '',
  '    it("should revert deposit to zero address", async function () {',
  '      const amount = ethers.parseUnits("100", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), amount);',
  '      await expect(',
  '        vault.connect(user).deposit(amount, ethers.ZeroAddress)',
  '      ).to.be.revertedWithCustomError(vault, "ZeroAddress");',
  '    });',
  '  });',
  '',
  '  describe("maxTotalDeposits", function () {',
  '    it("should enforce max total deposits", async function () {',
  '      const cap = ethers.parseUnits("500", 6);',
  '      await vault.connect(admin).setTotalDepositCap(cap);',
  '      const depositAmount = ethers.parseUnits("600", 6);',
  '      await asset.connect(user).approve(await vault.getAddress(), depositAmount);',
  '      await expect(',
  '        vault.connect(user).deposit(depositAmount, user.address)',
  '      ).to.be.revertedWithCustomError(vault, "CapExceedsCurrentBalance");',
  '    });',
  '  });',
  '});',
  ''
];

fs.writeFileSync('test/PiggyVault.test.ts', content.join('\n'));
console.log('OK', fs.statSync('test/PiggyVault.test.ts').size, 'bytes');
